echo -e '\e['$1'm ++++++++++\e[0m'
echo -e '\e['$1'm#####+++++++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm##        ++\e[0m'
echo -e '\e['$1'm#######+++++\e[0m'
echo -e '\e['$1'm ##########\e[0m'

